name: Blacklist monitor issue

on:
  push:  # This will run the action on every push, adjust as necessary
    paths:
      - 'blacklists.fqdn.urls'
      - 'updated.blacklists.urls'
  workflow_dispatch:

jobs:
  check-differences:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compare files and create an issue if different
      run: |
        DIFF=$(comm -23 <(sort blacklists.fqdn.urls) <(sort updated.blacklists.urls))  # Compare files after sorting them
        if [ "$DIFF" != "" ]; then
          echo "Differences detected. Opening an issue..."
          echo "$DIFF" > diff.txt
          ISSUE_BODY=$(echo -e "Differences detected between blacklist.fqdn.urls and updated.blacklists.urls:\n\n\`\`\`$DIFF\`\`\`")
          echo "$ISSUE_BODY" > issue_body.txt
    
          gh issue create --title "Differences detected in updated.blacklists.urls" --body-file issue_body.txt --label lists
        else
          echo "No differences detected."
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
