name: Node.js Proxy Server

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install http-proxy
    - name: Run Proxy Server
      run: |
        const http = require('http');
        const httpProxy = require('http-proxy');

        // New Proxy Server
        const proxy = httpProxy.createProxyServer();

        // Target URL
        const targetUrl = 'https://remote.url';

        http.createServer((req, res) => {
          proxy.web(req, res, { target: targetUrl, changeOrigin: true }, function(e) {
            console.log(`Error: ${e}`);
          });
        }).listen(8000);

        console.log(`Proxy server is running on port 8000 and proxying ${targetUrl}`);
